### ISSUE TITLE
Dockerfile slicer-notebook error Jupyter-server

### ISSUE THREAD

**Issue by JanAlexanderPersonal** [Slicer/SlicerDocker#39]
When building the slicer-notebook docker from the dockerfile, this fails at line 127:
```
RUN /home/sliceruser/Slicer/bin/PythonSlicer -m pip install --upgrade websockify && \
    cp /usr/lib/rebind.so /home/sliceruser/Slicer/lib/Python/lib/python3.6/site-packages/websockify/ && \
    /home/sliceruser/Slicer/bin/PythonSlicer -m pip install -e \
        git+https://github.com/lassoan/jupyter-desktop-server#egg=jupyter-desktop-server \
        git+https://github.com/jupyterhub/jupyter-server-proxy#egg=jupyter-server-proxy
```
With error message 

```
ERROR: Could not build wheels for jupyter-server-proxy which use PEP 517 and cannot be installed directly
```

Second point: The build complains about pip needing an update:
```
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
```

**Comment by lassoan** [comment]
Probably jupyter-server-proxy has been updated and no longer compatible with this pip version. You can try to upgrade pip in a previous command or use a specific hash for getting a jupyter-server-proxy version that still works (something like a version from a year ago).

**Comment by JanAlexanderPersonal** [comment]
Thank you , I will try that.
