### ISSUE TITLE
Multiple docker instances on same VM

### ISSUE THREAD

**Issue by vesaalexandru95** [Slicer/SlicerDocker#51]
Hello !
I'm trying to run 2 docker instances with different ports.
The default with 8888 and other one with another port. When I tried to change the port nothing happened.

How should I approach this?

Thanks !

**Comment by lassoan** [comment]
We don't do anything special. You can set up port and folder mapping for Slicer docker images as for any other image.

We might be able to help you, but we need much more details about what you do (information about your environment, docker image, and every command you execute).

**Comment by vesaalexandru95** [comment]
Hello @lassoan  . Thanks for the answer. I have managed to solve it.
