### ISSUE TITLE
SlicerRT

### ISSUE THREAD

**Issue by vesaalexandru95** [Slicer/SlicerDocker#53]
Hello !
I have a problem when I'm trying to upload an RT dicom into slicer docker version. I have installed the SlicerRT plugin.

Does anybody know which can be the problem?

**Comment by pieper** [comment]
You should try the same data on slicer desktop and if you can replicate it post a anonymous example that replicates the issue to the SlicerRT repo issues.  If it's really specific to docker then reopen this issue.

https://slicer.readthedocs.io/en/latest/user_guide/modules/dicom.html#troubleshooting

**Comment by vesaalexandru95** [comment]
Hello ! The same data is working on desktop version.

Thanks,
Alex

**Comment by pieper** [comment]
Hmm, then it may have to do with mapping the volume.  The dicom database contains paths to the actual data, and if those are not available the data won't load.

**Comment by vesaalexandru95** [comment]
These are the errors from the docker :
![image](https://user-images.githubusercontent.com/37544969/197270657-0fe8557e-07b3-48c3-94b2-84f554a59848.png)

**Comment by lassoan** [comment]
It seems that you are trying to load a DICOM image using "Add data" window. DICOM data must be loaded using the DICOM module. See code snippet for it here: https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#load-dicom-files-into-the-scene-from-a-folder

**Comment by vesaalexandru95** [comment]
Ok. Good. 
Now I get this error for the RT structure:
![image](https://user-images.githubusercontent.com/37544969/197272428-36d6fcd1-7c70-41e5-b340-7bd3a5a9065b.png)

**Comment by vesaalexandru95** [comment]
Hello again !
I've tried with the code from the documentation and I get the same error:
![image](https://user-images.githubusercontent.com/37544969/197331734-6a703e6f-2b86-4c8e-b142-a3cdd3147bfa.png)

**Comment by lassoan** [comment]
Could you try with the very latest Slicer Preview Release?
