### ISSUE TITLE
Problem with Slicer plugin in docker

### ISSUE THREAD

**Issue by vesaalexandru95** [Slicer/SlicerDocker#54]
Hello !
I'm trying to load RT structures in 3D slicer . I'm using the docker version for linux. 
I've tried several methods. The last one is to create a temporary DB and trying to import the data from there, but no success.
![image](https://user-images.githubusercontent.com/37544969/197332796-f1e68013-b087-4325-b16b-f9bd3a3064b3.png)
Thanks a lot for your help !

**Comment by lassoan** [comment]
You need to install the SlicerRT extension. See code snippet for extension installation in the script repository.
